[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:00:05Z

App            Version  Status  Scale  Charm    Channel  Rev  Exposed  Message
config-server           active      3  mongodb             0  no       
shard-one               active      3  mongodb  6/edge   191  no       
shard-two               active      3  mongodb  6/edge   191  no       

Unit              Workload  Agent  Machine  Public address  Ports            Message
config-server/0*  active    idle   0        10.41.105.136   27017-27018/tcp  
config-server/1   active    idle   1        10.41.105.58    27017-27018/tcp  
config-server/2   active    idle   2        10.41.105.23    27017-27018/tcp  
shard-one/0*      error     idle   3        10.41.105.190   27017/tcp        hook failed: "sharding-relation-changed"
shard-one/1       error     idle   4        10.41.105.106   27017/tcp        hook failed: "sharding-relation-changed"
shard-one/2       error     idle   5        10.41.105.104   27017/tcp        hook failed: "sharding-relation-changed"
shard-two/0       error     idle   6        10.41.105.40    27017/tcp        hook failed: "sharding-relation-changed"
shard-two/1       error     idle   7        10.41.105.160   27017/tcp        hook failed: "sharding-relation-changed"
shard-two/2*      error     idle   8        10.41.105.249   27017/tcp        hook failed: "sharding-relation-changed"

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.41.105.136  juju-a2acb5-0  ubuntu@22.04      Running
1        started  10.41.105.58   juju-a2acb5-1  ubuntu@22.04      Running
2        started  10.41.105.23   juju-a2acb5-2  ubuntu@22.04      Running
3        started  10.41.105.190  juju-a2acb5-3  ubuntu@22.04      Running
4        started  10.41.105.106  juju-a2acb5-4  ubuntu@22.04      Running
5        started  10.41.105.104  juju-a2acb5-5  ubuntu@22.04      Running
6        started  10.41.105.40   juju-a2acb5-6  ubuntu@22.04      Running
7        started  10.41.105.160  juju-a2acb5-7  ubuntu@22.04      Running
8        started  10.41.105.249  juju-a2acb5-8  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

machine-0: 01:41:54 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:41:54 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-config-server-0: 01:41:54 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:41:55 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:41:55 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-config-server-1: 01:41:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:41:58 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:41:58 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-config-server-2: 01:41:58 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:42:01 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:42:01 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-one-0: 01:42:01 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:42:03 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:42:03 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-one-2: 01:42:03 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-8: 01:42:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-8: 01:42:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-two-2: 01:42:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:42:06 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:42:06 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-one-1: 01:42:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-6: 01:42:08 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 01:42:08 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-two-0: 01:42:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-7: 01:42:08 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-7: 01:42:08 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-two-1: 01:42:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-shard-one-0: 01:43:24 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crjoq9scr6li110vbmig seems to have no observers, could be removed
unit-shard-two-2: 01:43:28 ERROR unit.shard-two/2.juju-log _on_secret_remove: Secret secret:crjoqakcr6li110vbmj0 seems to have no observers, could be removed
unit-shard-one-0: 01:43:31 ERROR unit.shard-one/0.juju-log database-peers:2: Charm is in sharding role: database. Does not support shard interface.
unit-shard-two-2: 01:43:33 ERROR unit.shard-two/2.juju-log database-peers:4: Charm is in sharding role: database. Does not support shard interface.
unit-shard-one-0: 01:43:41 ERROR unit.shard-one/0.juju-log database-peers:2: Charm is in sharding role: database. Does not support shard interface.
unit-shard-two-2: 01:43:42 ERROR unit.shard-two/2.juju-log database-peers:4: Charm is in sharding role: database. Does not support shard interface.
unit-config-server-0: 01:44:18 ERROR unit.config-server/0.juju-log _on_secret_remove: Secret secret:crjoq6kcr6li110vbmi0 seems to have no observers, could be removed
unit-config-server-0: 01:45:17 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard shard-one to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726451116, 1), 'signature': {'hash': b'qW\\n\\x1e\\x9a\\x13\\x16m\\x96\\xd9\\xd0\\xac[\\xa3\\xfb\\xae\\x18\\x9ck\\xac', 'keyId': 7415050501542117380}}, 'operationTime': Timestamp(1726451116, 1)}")
unit-config-server-0: 01:45:17 ERROR unit.config-server/0.juju-log config-server:6: shard-one shard does not have the same auth as the config server.
unit-config-server-0: 01:45:33 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard shard-one to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1726451133, 1), \'signature\': {\'hash\': b\'\\x8b\\xfe\\xf6\\xa8\\x97\\xde\\x0f\\xc5}\\xa6{\\xd5i\\xc8\\r\\x1f/\\xae\\xc8\\xf2\', \'keyId\': 7415050501542117380}}, \'operationTime\': Timestamp(1726451133, 1)}')
unit-config-server-0: 01:45:34 ERROR unit.config-server/0.juju-log config-server:6: Failed to add shard-one to cluster
unit-config-server-0: 01:45:34 ERROR unit.config-server/0.juju-log config-server:6: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-one, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-one\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1726451133, 1), \'signature\': {\'hash\': b\'\\x8b\\xfe\\xf6\\xa8\\x97\\xde\\x0f\\xc5}\\xa6{\\xd5i\\xc8\\r\\x1f/\\xae\\xc8\\xf2\', \'keyId\': 7415050501542117380}}, \'operationTime\': Timestamp(1726451133, 1)}')
unit-config-server-0: 01:45:57 ERROR unit.config-server/0.juju-log config-server:7: Failed to add shard shard-two to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726451156, 1), 'signature': {'hash': b'\\xc6c\\xef\\xa0\\x11.\\xd5z\\x9a\\xde[[\\xc5+\\xa1\\xbc\\x95ugY', 'keyId': 7415050501542117380}}, 'operationTime': Timestamp(1726451156, 1)}")
unit-config-server-0: 01:45:57 ERROR unit.config-server/0.juju-log config-server:7: shard-two shard does not have the same auth as the config server.
unit-shard-one-0: 01:45:58 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crjoq9scr6li110vbmig seems to have no observers, could be removed
unit-shard-one-0: 01:46:03 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crjoq9scr6li110vbmig seems to have no observers, could be removed
unit-shard-one-0: 01:46:07 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crjoq9scr6li110vbmig seems to have no observers, could be removed
unit-config-server-0: 01:46:13 ERROR unit.config-server/0.juju-log config-server:7: Failed to add shard shard-two to the config server, error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-two, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-two\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1726451173, 1), \'signature\': {\'hash\': b\'\\x1d\\xa4\\xebXu\\xc9\\x14\\x91r\\xd7\\x1c\\x87\\x08\\x9d\\x80\\xf9\\xf9S\\x14\\xf8\', \'keyId\': 7415050501542117380}}, \'operationTime\': Timestamp(1726451173, 1)}')
unit-config-server-0: 01:46:13 ERROR unit.config-server/0.juju-log config-server:7: Failed to add shard-two to cluster
unit-config-server-0: 01:46:13 ERROR unit.config-server/0.juju-log config-server:7: Deferring _on_relation_event for shards interface since: error=OperationFailure('Could not find host matching read preference { mode: "primary" } for set shard-two, full error: {\'ok\': 0.0, \'errmsg\': \'Could not find host matching read preference { mode: "primary" } for set shard-two\', \'code\': 133, \'codeName\': \'FailedToSatisfyReadPreference\', \'$clusterTime\': {\'clusterTime\': Timestamp(1726451173, 1), \'signature\': {\'hash\': b\'\\x1d\\xa4\\xebXu\\xc9\\x14\\x91r\\xd7\\x1c\\x87\\x08\\x9d\\x80\\xf9\\xf9S\\x14\\xf8\', \'keyId\': 7415050501542117380}}, \'operationTime\': Timestamp(1726451173, 1)}')
unit-shard-two-2: 01:46:39 ERROR unit.shard-two/2.juju-log _on_secret_remove: Secret secret:crjoqakcr6li110vbmj0 seems to have no observers, could be removed
unit-shard-one-0: 01:46:39 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crjoq9scr6li110vbmig seems to have no observers, could be removed
unit-shard-two-2: 01:46:40 ERROR unit.shard-two/2.juju-log _on_secret_remove: Secret secret:crjoqakcr6li110vbmj0 seems to have no observers, could be removed
unit-shard-two-2: 01:47:18 ERROR unit.shard-two/2.juju-log Charm is in sharding role: database. Does not support shard interface.
unit-shard-one-0: 01:47:43 ERROR unit.shard-one/0.juju-log Charm is in sharding role: database. Does not support shard interface.
unit-shard-two-2: 01:48:02 ERROR unit.shard-two/2.juju-log _on_secret_remove: Secret secret:crjoqakcr6li110vbmj0 seems to have no observers, could be removed
unit-shard-two-2: 01:52:32 ERROR unit.shard-two/2.juju-log _on_secret_remove: Secret secret:crjoqakcr6li110vbmj0 seems to have no observers, could be removed
unit-shard-two-2: 01:53:02 ERROR unit.shard-two/2.juju-log Charm is in sharding role: database. Does not support shard interface.
unit-shard-one-0: 01:53:37 ERROR unit.shard-one/0.juju-log Charm is in sharding role: database. Does not support shard interface.
unit-shard-two-2: 01:57:33 ERROR unit.shard-two/2.juju-log Charm is in sharding role: database. Does not support shard interface.
unit-shard-two-1: 01:57:45 ERROR unit.shard-two/1.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-0: 01:57:45 ERROR unit.shard-one/0.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-2: 01:57:45 ERROR unit.shard-two/2.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-0: 01:57:45 ERROR unit.shard-two/0.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-1: 01:57:45 ERROR unit.shard-one/1.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-1: 01:57:46 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:57:46 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-2: 01:57:46 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-0: 01:57:46 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-1: 01:57:46 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-2: 01:57:47 ERROR unit.shard-one/2.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-2: 01:57:48 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-1: 01:57:51 ERROR unit.shard-two/1.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-2: 01:57:51 ERROR unit.shard-two/2.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-0: 01:57:51 ERROR unit.shard-one/0.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-1: 01:57:51 ERROR unit.shard-one/1.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-0: 01:57:51 ERROR unit.shard-two/0.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-1: 01:57:52 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-2: 01:57:52 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:57:52 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-1: 01:57:52 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-0: 01:57:52 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-2: 01:57:53 ERROR unit.shard-one/2.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-2: 01:57:54 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-2: 01:58:02 ERROR unit.shard-two/2.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-1: 01:58:02 ERROR unit.shard-one/1.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-1: 01:58:02 ERROR unit.shard-two/1.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-0: 01:58:02 ERROR unit.shard-one/0.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-2: 01:58:02 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-0: 01:58:03 ERROR unit.shard-two/0.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-1: 01:58:03 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:58:03 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-1: 01:58:03 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-0: 01:58:03 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-2: 01:58:04 ERROR unit.shard-one/2.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-2: 01:58:04 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-2: 01:58:22 ERROR unit.shard-two/2.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-2: 01:58:23 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-1: 01:58:23 ERROR unit.shard-one/1.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-1: 01:58:23 ERROR unit.shard-two/1.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-1: 01:58:23 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-1: 01:58:24 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:58:24 ERROR unit.shard-one/0.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-0: 01:58:24 ERROR unit.shard-two/0.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-0: 01:58:24 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-0: 01:58:24 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-2: 01:58:25 ERROR unit.shard-one/2.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-2: 01:58:25 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-2: 01:59:02 ERROR unit.shard-two/2.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-2: 01:59:03 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-0: 01:59:04 ERROR unit.shard-two/0.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-1: 01:59:04 ERROR unit.shard-one/1.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-0: 01:59:04 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-1: 01:59:04 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-two-1: 01:59:05 ERROR unit.shard-two/1.juju-log sharding:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-two-1/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-two-1/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-two-1: 01:59:05 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:59:05 ERROR unit.shard-one/0.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-0/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-0/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-0: 01:59:06 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-2: 01:59:07 ERROR unit.shard-one/2.juju-log sharding:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1597, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 698, in _on_relation_changed
    if not self.pass_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 746, in pass_hook_checks
    if not self.pass_sanity_hook_checks(event):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v1/shards_interface.py", line 785, in pass_sanity_hook_checks
    if not self.charm.is_relation_feasible(self.relation_name):
  File "/var/lib/juju/agents/unit-shard-one-2/charm/./src/charm.py", line 1539, in is_relation_feasible
    if revision_mismatch_status := self.status.get_cluster_mismatched_revision_status():
  File "/var/lib/juju/agents/unit-shard-one-2/charm/lib/charms/mongodb/v0/set_status.py", line 267, in get_cluster_mismatched_revision_status
    self.get_config_server_name()
AttributeError: 'MongoDBStatusHandler' object has no attribute 'get_config_server_name'
unit-shard-one-2: 01:59:07 ERROR juju.worker.uniter.operation hook "sharding-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-shard-one-0: 01:59:59 ERROR unit.shard-one/0.juju-log Cluster is not healthy

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...