{"uid":"f12fefe4213d79fa","name":"test_storage_re_use","fullName":"tests.integration.ha_tests.test_ha#test_storage_re_use","historyId":"163d64357549dfd513cdd997aa331355","time":{"start":1725500645801,"stop":1725500645801,"duration":0},"description":"Verifies that database units with attached storage correctly repurpose storage.\n\n    It is not enough to verify that Juju attaches the storage. Hence test checks that the mongod\n    properly uses the storage that was provided. (ie. doesn't just re-sync everything from\n    primary, but instead computes a diff between current storage and primary storage.)\n    ","descriptionHtml":"<p>Verifies that database units with attached storage correctly repurpose storage.</p>\n<pre><code>It is not enough to verify that Juju attaches the storage. Hence test checks that the mongod\nproperly uses the storage that was provided. (ie. doesn't just re-sync everything from\nprimary, but instead computes a diff between current storage and primary storage.)\n</code></pre>\n","status":"skipped","statusMessage":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 90, in pytest_runtest_setup\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 842, in pytest_runtest_setup\n    yield from self._runtest_for(item, \"setup\")\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 874, in pytest_runtest_setup\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 87, in pytest_runtest_setup\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 160, in pytest_runtest_setup\n    item.session._setupstate.setup(item)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 514, in setup\n    col.setup()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1630, in setup\n    self._request._fillfixtures()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 696, in _fillfixtures\n    item.funcargs[argname] = self.getfixturevalue(argname)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 531, in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 616, in _get_active_fixturedef\n    fixturedef.execute(request=subrequest)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1090, in execute\n    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pytest_operator/plugin.py\", line 234, in abort_on_fail\n    pytest.xfail(\"aborted\")\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/outcomes.py\", line 206, in xfail\n    raise XFailed(reason)\n_pytest.outcomes.XFailed: aborted","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1725500624810,"stop":1725500624811,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1725500624811,"stop":1725500624811,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1725500624811,"stop":1725500624975,"duration":164},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1725500645801,"stop":1725500645801,"duration":0},"status":"failed","statusMessage":"_pytest.outcomes.XFailed: aborted\n","statusTrace":"  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/pytest_operator/plugin.py\", line 234, in abort_on_fail\n    pytest.xfail(\"aborted\")\n  File \"/home/ubuntu/actions-runner/_work/mongodb-operator/mongodb-operator/.tox/integration/lib/python3.10/site-packages/_pytest/outcomes.py\", line 206, in xfail\n    raise XFailed(reason)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[{"name":"ops_test::finalizer","time":{"start":1725500645833,"stop":1725500646173,"duration":340},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1725500646174,"stop":1725500646174,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1725500646174,"stop":1725500646174,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1725500646174,"stop":1725500646174,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"runner(['self-hosted', 'linux', 'X64', 'jammy', 'large'])"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.ha_tests"},{"name":"suite","value":"test_ha"},{"name":"host","value":"github-runner"},{"name":"thread","value":"11725-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.ha_tests.test_ha"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"bcc804ba6591773c","status":"unknown","time":{}}],"categories":[],"history":{"statistic":{"failed":0,"broken":1,"skipped":35,"passed":0,"unknown":2,"total":38},"items":[{"uid":"5bf0cd1405866d4e","reportUrl":"../2228//#testresult/5bf0cd1405866d4e","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1725413909588,"stop":1725413909588,"duration":0}},{"uid":"cf19f5e5ed1002aa","reportUrl":"../2218//#testresult/cf19f5e5ed1002aa","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1725327804295,"stop":1725327804493,"duration":198}},{"uid":"460ac899d3aa9129","reportUrl":"../2207//#testresult/460ac899d3aa9129","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1725241400099,"stop":1725241400300,"duration":201}},{"uid":"d14d41aea5a2bb70","reportUrl":"../2206//#testresult/d14d41aea5a2bb70","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1725155428117,"stop":1725155428343,"duration":226}},{"uid":"ba93b7bf13575ad5","reportUrl":"../2205//#testresult/ba93b7bf13575ad5","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1725068620009,"stop":1725068620219,"duration":210}},{"uid":"925c559a6c077f55","reportUrl":"../2191//#testresult/925c559a6c077f55","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724982156535,"stop":1724982156728,"duration":193}},{"uid":"71c306c2e2ef1a89","reportUrl":"../2186//#testresult/71c306c2e2ef1a89","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724895831790,"stop":1724895832040,"duration":250}},{"uid":"205340e68da201bf","reportUrl":"../2183//#testresult/205340e68da201bf","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724809346091,"stop":1724809346303,"duration":212}},{"uid":"a216b1a6c65dfd07","reportUrl":"../2182//#testresult/a216b1a6c65dfd07","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724722953617,"stop":1724722953787,"duration":170}},{"uid":"119597d87e29fafd","reportUrl":"../2181//#testresult/119597d87e29fafd","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724636499467,"stop":1724636499679,"duration":212}},{"uid":"db5bd0844df7cb0c","reportUrl":"../2180//#testresult/db5bd0844df7cb0c","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724550132292,"stop":1724550132471,"duration":179}},{"uid":"a648e7b568ac7a1c","reportUrl":"../2179//#testresult/a648e7b568ac7a1c","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724463684029,"stop":1724463684212,"duration":183}},{"uid":"e36e85982bc4a2d6","reportUrl":"../2173//#testresult/e36e85982bc4a2d6","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724378717613,"stop":1724378717814,"duration":201}},{"uid":"4302c2a9035e0013","reportUrl":"../2163//#testresult/4302c2a9035e0013","status":"unknown","time":{}},{"uid":"2b85493a147a0b15","reportUrl":"../2152//#testresult/2b85493a147a0b15","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724204486858,"stop":1724204487421,"duration":563}},{"uid":"4ceb391d8f1517f6","reportUrl":"../2126//#testresult/4ceb391d8f1517f6","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724117894291,"stop":1724117894482,"duration":191}},{"uid":"6d3f5ea3004b6a75","reportUrl":"../2113//#testresult/6d3f5ea3004b6a75","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1724031641170,"stop":1724031641378,"duration":208}},{"uid":"19a1c3b9fd2f82ec","reportUrl":"../2112//#testresult/19a1c3b9fd2f82ec","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1723945421117,"stop":1723945421350,"duration":233}},{"uid":"afacf67ec053f34e","reportUrl":"../2111//#testresult/afacf67ec053f34e","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1723858664311,"stop":1723858664529,"duration":218}},{"uid":"b4e4c81ccbf630a9","reportUrl":"../2102//#testresult/b4e4c81ccbf630a9","status":"skipped","statusDetails":"Skipped: reuse of storage can only be used on deployments with persistent storage not on rootfs deployments","time":{"start":1723772847205,"stop":1723772848231,"duration":1026}}]},"tags":["runner(['self-hosted', 'linux', 'X64', 'jammy', 'large'])","asyncio","abort_on_fail","group(1)"]},"source":"f12fefe4213d79fa.json","parameterValues":[]}